"""empty message

Revision ID: eebf232d88bb
Revises: 6cfe4c5913d7
Create Date: 2022-06-12 17:35:38.663000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebf232d88bb'
down_revision = '6cfe4c5913d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('instrument', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'instrument')
    # ### end Alembic commands ###
